aws-quickstart/quickstart-atlassian-bitbucket

templates/BitbucketDataCenter.template
templates/quickstart-bitbucket-master.template

This pull request contains the following changes: 
- Remove `Conditions` from `quickstart-bitbucket-master.template`, as they are not used
- Group parameters in the `quickstart-bitbucket-master.template` the same as in `BitbucketDataCenter.template`
- Re-add `Default` values for `HomeIops` and `DbIops` to ensure the templates can be launched without provisioned IOPS (would otherwise fail on parameter validation)
- Add `ExternalSubnets` to `BitbucketDataCenter.template` to allow `LoadBalancer` to be deployed in public facing subnet
- Rename `Subnets` in `BitbucketDataCenter.template` to `InternalSubnets`
- Make `quickstart-bitbucket-master.template` deploy internal infrastructure into the private subnets

Atlassian feedback

---

templates/BitbucketDataCenter.template

These are some small tweaks we have made to the `BitbucketDataCenter` template. 
Namely:
- added the `FileServer` to the allowed roles for Elasticsearch (will be used for backup)
- added the `m4.16xlarge` instance type as an option for the `FileServer`
- removed the unused `AWSRegionArch2ElasticsearchAMI` mapping

Tweaks to BitbucketDataCenter template

---

templates/BitbucketDataCenter.template

When the rename of the session policy was done, the SSL policy name was
missed. This means that when setting up the application with SSL, the
template fails to create, as it cannot find the `JSessionIdStickiness`
policy.
This also updates the AMI IDs to the latest public AMI.

Update `JSessionIdStickiness` to `SessionStickiness` policy

---

templates/BitbucketDataCenter.template

The previous update only update the kernel to a kernel with KPTI protection and not the other mitigations required to prevent spectre/meltdown exceptions.

Upgrade to linux kernel that contains patches for spectre/metldown

---

templates/BitbucketDataCenter.template

Based on the changes mentioned in the "upgrade" section of this README: https://bitbucket.org/atlassianlabs/atlassian-bitbucket-diy-backup/src/master/README.md
and the updated example configs in the same repo.

NONE: updated bitbucket.diy-backup.vars.sh to match the new (6.0) backup scripts

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

We decommissioned Postgres 9.3 in Bitbucket Server 6.x (about to be released soon), but the AMIs still had the Postgres version set to 9.3 so our templates won't work with BbS 6.0 and above. This change upgrades the Postgres version to 9.6.

Update AMIs to upgrade Postgres version to 9.6

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

* add SSM policy and install SSM agent on the instance
* update default instance type to c5.xlarge
* update available instance families
* lexicographical ordering for parameters

DCD-323: Add SSM and update instance type familes

---

templates/quickstart-bitbucket-dc.template.yaml

More information: https://alas.aws.amazon.com/ALAS-2019-1205.html

DCD-345: Update AMIs kernel version to `4.14.114-83.126.amzn1.x86_64`

---

README.md

This PR converts the Quickstart to use the official Amazon Linux 2 AMIs. All post-installation application configuration is now handled by external Ansible roles & playbooks. The Ansible repository is here:
https://bitbucket.org/atlassian/dc-deployments-automation/src/master/
The use of official AMIs is common request from organisations that have restrictions on which AMIs they can use, and the separation of infrastructure and application configuration should increase flexibility, development speed, and simplify security updates to AMIs.
This also removes a number of unused and obsolete parameters, while adding parameters to customise the initialisation repository.

DCD-386: Convert Quickstart to use Amazon AMIs and Ansible-based node deployment.

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

Change AssociatePublicIPAddress parameter to InternetFacingLoadBalancer and update description so it is less misleading
We had reports of customers not being able to access their instance because they set AssociatePublicIPAddress to false, thinking it would make their EC2 instances publicly accessible if it were true. In reality it just controls the load balancer scheme.

Update AssociatePublicIPAddress parameter

---

.cfnlintrc
templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

*Issue #, if available:*
DCD-578
DCD-289
*Description of changes:*
For some reason, the expected EBS volume is not created on the NFS fileserver. This isn't just unattached, it's not created in the region at all. This seems to be limited to some regions; Frankfurt and Oregon silently fail, Sydney works. The deployment isn't failing though.
* Changes NFS volume mapping
* Fixes `cfn-lintin` linting issues
https://github.com/atlassian/quickstart-atlassian-bitbucket/pull/13
https://github.com/atlassian/quickstart-atlassian-bitbucket/pull/11

DCD-578: Bitbucket is failing due to missing EBS volume in some regions

---

.cfnlintrc
ci/params/default/quickstart-bitbucket-default.json
ci/params/default/taskcat.yml
ci/quickstart-bitbucket-master-v5.json
templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

*Description of changes:*
* Added default `taskcat` param file
* Quoted JDBC and Postgres passwords in `/etc/atl` - DCD-547
* Workaround for autogenerated `taskcat` passwords containing forbidden characters

DCD-595: Add default taskcat build and fix EBS VolumeType & password quoting

---

ci/params/3nodes/quickstart-bitbucket-3nodes.json
ci/params/3nodes/taskcat.yml
templates/quickstart-bitbucket-dc.template.yaml

DCD-945: Use single AZ for Bitbucket application nodes
*Description of changes:*
Application nodes were supposed to run only in single Availability Zone. This change creates all Bitbucket nodes in the same AZ as FileServer.

DCD-945: Use single AZ for Bitbucket application nodes

---

templates/quickstart-bitbucket-dc.template.yaml

*Issue #, if available:*
*Description of changes:*
`DatabaseIdentifier` was removed from ASI and the change wasn't reflected.

Remove unnecessary DatabaseIdentifier

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

Imports the private IP of the bastion host from the ASI so that when CidrBlock is set the Bastion can still SSH to the webserver.

DCD-954: Add bastion to EC2 security group

---

.taskcat.yml
templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

Using the stack name as the db instance identifier doesn't work if the stack name is longer than 60 chars. We use a custom resource to trim it down.

Ensure db instance name is within character limit

---

.taskcat.yml

Ran custom Jira CI plan (temporarily updated Jira submodules to point to updated quickstart-atlassian-services and updated quickstart-amazon-aurora) results for which are below:
https://server-syd-bamboo.internal.atlassian.com/browse/DCD-AWSJIRA64-JSMOKDEPLOY-9/log
Deploys passed and all but the HTTP acceptance tests which I believe to be a dud (looking at the logs). This run should confirm these AWS partition changes across the board for Jira and the other products; BB, Connie, Crowd
These changes have also been tested in a Gov account and are shown to work, where we no longer have failing deployments

DCD-1051: Gov arn for gov region

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

The valid bitbucket.properties values can include commas (e.g hazelcast.network.tcpip.members), so using a comma-separated list will mangle these. Move to spaces, and leave decoding to the playbook roles. There are no backwards-compatibility issues with this change as we never honoured this parameter, and it wouldn't have worked anyway, as the current encoding in /etc/atl strips any delimiters.
There is a corresponding PR in the playbook repository.

DCD-1190: Change the BitbucketProperties to a simple space-delimited string

---

.cfnlintrc
.gitmodules
.taskcat.yml
ci/params/3nodes/quickstart-bitbucket-3nodes.json
ci/params/aurora/quickstart-bitbucket-dc-aurora-params.json
ci/params/automated-setup/quickstart-bitbucket-automated-setup.json
ci/params/dbVersions/quickstart-bitbucket-aurora-10.json
ci/params/dbVersions/quickstart-bitbucket-aurora-12.json
ci/params/dbVersions/quickstart-bitbucket-postgres-10.json
ci/params/dbVersions/quickstart-bitbucket-postgres-11.json
ci/params/dbVersions/quickstart-bitbucket-postgres-12.json
ci/params/default/quickstart-bitbucket-default.json
ci/params/insecure-search/quickstart-bitbucket-default.json
ci/params/insecure-search/taskcat.yml
ci/params/jvm-support-opts/quickstart-bitbucket-jvm-support-opts.json
ci/params/no-bastion/quickstart-bitbucket-no-bastion.json
ci/params/ssl-and-dns/quickstart-bitbucket-ci-params.json
ci/quickstart-bitbucket-master.json
templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

* Update default Postgres version to 12
* Update Postgres patch versions for all supported Postgres engines
* Allow support for more secure elasticsearch
* Deploy within VPC
* Use fine-grained access controls
* Encryption at rest
* Enforce HTTPS

February Quick Start Updates

---

templates/quickstart-bitbucket-dc-with-vpc.template.yaml
templates/quickstart-bitbucket-dc.template.yaml

Description of the 'key Pairs Name SSH' field modified to reduce the confusion during Quickstart set up.

DCD-1316: SSH Key Pairs Name direction changed to avoid confusion.
